'use strict';
const $=s=>document.querySelector(s),map=$('#map'),surface=$('#map-surface'),dialog=$('#poster-dialog'),helpDialog=$('#help-dialog');
const islandPoints=[[19,20],[21,50],[20,80],[49,68],[60,25],[62,84],[83,50],[86,84]];regions.forEach((r,i)=>{[r.x,r.y]=islandPoints[i];});
const posterPath=p=>`assets/posters/${p.id}.png`;
let camera={x:50,y:50,zoom:innerWidth<=760?1.35:1},posterIndex=0,filter=null,drag=null,scenePaused=false,mapPaused=false,sceneFrame=0,mapFrame=0,lastScene=0,lastMap=0,loadVersion=0,sceneReady=false,mapReady=false,storyEnded=false;
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
let visited=new Set();try{visited=new Set(JSON.parse(localStorage.getItem('shell-atlas-visited')||'[]'));}catch{}
function geometry(){const r=map.getBoundingClientRect(),fit=Math.min(r.width/1600,r.height/1200);return{w:1600*fit*camera.zoom,h:1200*fit*camera.zoom,vw:r.width,vh:r.height};}
function paintCamera(){const g=geometry(),limit=(v,size,view)=>size<=view?50:Math.max(view/size*50,Math.min(100-view/size*50,v));camera.x=limit(camera.x,g.w,g.vw);camera.y=limit(camera.y,g.h,g.vh);surface.style.width=g.w+'px';surface.style.height=g.h+'px';surface.style.left=g.vw/2-camera.x/100*g.w+'px';surface.style.top=g.vh/2-camera.y/100*g.h+'px';$('#zoom-out').disabled=camera.zoom<=1;$('#zoom-in').disabled=camera.zoom>=3;}
function zoom(d){camera.zoom=Math.max(1,Math.min(3,camera.zoom+d));paintCamera();}
const destinationPoints=[[23,15],[32,20],[25,42],[15,49],[26,50],[35,55],[24,60],[14,59],[7,54],[23,73],[30,83],[12,87],[51,67],[45,75],[65,20],[72,29],[65,83],[56,87],[88,46],[78,54],[85,85],[92,81],[80,92]];
function renderMarkers(){places.forEach((p,i)=>{const b=document.createElement('button');b.className='landmark destination-landmark';b.dataset.id=p.id;b.style.left=destinationPoints[i][0]+'%';b.style.top=destinationPoints[i][1]+'%';b.setAttribute('aria-label',`走进${p.name}`);b.innerHTML=`<span class="place-label">${p.en}</span>`;b.onclick=e=>{e.stopPropagation();openPoster(i);};$('#markers').append(b);});}
function updateVisited(){try{localStorage.setItem('shell-atlas-visited',JSON.stringify([...visited]));}catch{}$('#progress').textContent=`${visited.size} / 23`;renderNotebook();}
function renderNotebook(){$('#destinations').replaceChildren();for(const p of places.filter(p=>!filter||p.region===filter)){const b=document.createElement('button');b.className='destination';b.innerHTML=`<img src="${posterPath(p)}" alt="" loading="lazy"><span><strong>${p.name}</strong><small>${p.en}</small></span><span class="stamp ${visited.has(p.id)?'done':''}">${visited.has(p.id)?'已到访':String(p.number).padStart(2,'0')}</span>`;b.onclick=()=>{closeNotebook();openPoster(places.indexOf(p));};$('#destinations').append(b);}}
function renderRegions(){for(const r of [{id:null,name:'全部'},...regions]){let b=document.createElement('button');b.textContent=r.name;b.setAttribute('aria-pressed',String(r.id===filter));b.onclick=()=>{filter=r.id;$('#regions').replaceChildren();renderRegions();renderNotebook();};$('#regions').append(b);}}
function closeNotebook(){$('#collection').hidden=true;$('#collection-toggle').setAttribute('aria-expanded','false');}
function showFrame(el,frame){el.style.backgroundPosition=`${frame%3*50}% ${frame<3?0:100}%`;el.dataset.frame=String(frame);}
function setFilm(el,url){el.style.backgroundImage=`url('${url}')`;showFrame(el,0);}
function openPoster(i){posterIndex=(i+places.length)%places.length;const p=places[posterIndex],film=FILMS[p.id],version=++loadVersion;sceneReady=false;storyEnded=false;sceneFrame=0;lastScene=0;scenePaused=reduceMotion.matches;$('#poster-dialog').setAttribute('aria-label',p.name+'的逐帧故事');$('#story-film').setAttribute('aria-label',p.name+'：人物与环境共同变化的完整场景帧');$('#story-film').hidden=true;$('#story-loading').hidden=false;$('#story-error').hidden=true;$('#full-poster').hidden=true;$('#scene-stage').hidden=false;dialog.classList.remove('poster-view');$('#toggle-poster').setAttribute('aria-pressed','false');$('#pause-scene').setAttribute('aria-pressed',String(scenePaused));$('#pause-scene').textContent=scenePaused?'▷':'Ⅱ';$('#poster-image').src=posterPath(p);$('#poster-image').alt=p.name+'完整摄影与拼贴海报';if(!dialog.open)dialog.showModal();const image=new Image();image.onload=()=>{if(version!==loadVersion)return;sceneReady=true;$('#story-loading').hidden=true;$('#story-film').hidden=false;setFilm($('#story-film'),film.src);$('#scene-stage').style.setProperty('--film-ratio',(image.naturalWidth/3)/(image.naturalHeight/2));dialog.style.setProperty('--film-ratio',(image.naturalWidth/3)/(image.naturalHeight/2));visited.add(p.id);updateVisited();};image.onerror=()=>{if(version!==loadVersion)return;$('#story-loading').hidden=true;$('#story-error').hidden=false;};image.src=film.src;}
$('#close-poster').onclick=()=>dialog.close();$('#previous').onclick=()=>openPoster(posterIndex-1);$('#next').onclick=()=>openPoster(posterIndex+1);
$('#toggle-poster').onclick=()=>{const full=$('#full-poster').hidden;$('#full-poster').hidden=!full;$('#scene-stage').hidden=full;dialog.classList.toggle('poster-view',full);$('#toggle-poster').setAttribute('aria-pressed',String(full));$('#toggle-poster').setAttribute('aria-label',full?'回到逐帧故事':'查看完整海报');};$('#pause-scene').onclick=()=>{if(storyEnded){storyEnded=false;sceneFrame=0;showFrame($('#story-film'),0);lastScene=performance.now();scenePaused=true;}scenePaused=!scenePaused;$('#pause-scene').setAttribute('aria-pressed',String(scenePaused));$('#pause-scene').setAttribute('aria-label',scenePaused?'继续故事':'暂停故事');$('#pause-scene').textContent=scenePaused?'▷':'Ⅱ';};
$('#pause-map').onclick=()=>{mapPaused=!mapPaused;$('#pause-map').setAttribute('aria-pressed',String(mapPaused));$('#pause-map').setAttribute('aria-label',mapPaused?'继续地图微动':'暂停地图微动');$('#pause-map').textContent=mapPaused?'▷':'Ⅱ';};
$('#help').onclick=()=>helpDialog.showModal();$('#close-help').onclick=$('#start-walk').onclick=()=>helpDialog.close();$('#reset-visits').onclick=()=>{visited.clear();updateVisited();};$('#collection-toggle').onclick=()=>{const open=$('#collection').hidden;$('#collection').hidden=!open;$('#collection-toggle').setAttribute('aria-expanded',String(open));if(open)$('#close-collection').focus();};$('#close-collection').onclick=closeNotebook;
$('#overview').onclick=()=>{camera={x:50,y:50,zoom:1};paintCamera();};$('#zoom-in').onclick=()=>zoom(.3);$('#zoom-out').onclick=()=>zoom(-.3);$('#next-story').onclick=()=>{const p=places.find(p=>!visited.has(p.id));openPoster(p?places.indexOf(p):(posterIndex+1)%places.length);};
for(const d of [dialog,helpDialog])d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});
map.addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button!==0)return;drag={sx:e.clientX,sy:e.clientY,cx:camera.x,cy:camera.y};map.setPointerCapture(e.pointerId);});map.addEventListener('pointermove',e=>{if(!drag)return;const g=geometry();camera.x=drag.cx-(e.clientX-drag.sx)/g.w*100;camera.y=drag.cy-(e.clientY-drag.sy)/g.h*100;paintCamera();});map.addEventListener('pointerup',()=>drag=null);map.addEventListener('pointercancel',()=>drag=null);map.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?.12:-.12);},{passive:false});
window.addEventListener('keydown',e=>{if(dialog.open){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();openPoster(posterIndex+(e.key==='ArrowLeft'?-1:1));}else if(e.key===' '&&!e.target.closest('button')){e.preventDefault();$('#pause-scene').click();}return;}if(e.key==='Escape')closeNotebook();});
function frame(t){if(!document.hidden){if(dialog.open&&sceneReady&&!scenePaused&&!reduceMotion.matches&&$('#full-poster').hidden){const film=FILMS[places[posterIndex].id],duration=film.durations?.[sceneFrame]||film.frameMs||650;if(!lastScene)lastScene=t;if(t-lastScene>duration){if(film.playMode==='once'&&sceneFrame===5){storyEnded=true;scenePaused=true;$('#pause-scene').textContent='↻';$('#pause-scene').setAttribute('aria-label','重播故事');$('#pause-scene').setAttribute('aria-pressed','true');}else{sceneFrame=(sceneFrame+1)%6;showFrame($('#story-film'),sceneFrame);}lastScene=t;}}if(mapReady&&!mapPaused&&!reduceMotion.matches&&!dialog.open&&!helpDialog.open&&t-lastMap>1200){mapFrame=(mapFrame+1)%6;showFrame($('#map-film'),mapFrame);lastMap=t;}}requestAnimationFrame(frame);}
const mapImage=new Image();mapImage.onload=()=>{setFilm($('#map-film'),'assets/films/Map.png');$('#map-film').hidden=false;$('.map-art').hidden=true;mapReady=true;};mapImage.src='assets/films/Map.png';
new ResizeObserver(paintCamera).observe(map);renderMarkers();renderRegions();updateVisited();paintCamera();requestAnimationFrame(frame);
